#!/bin/sh
####################################################################
#
# output in results_Fe_afm1/
#

temp=./tmp4
pseudo=.
bin=$HOME/QE/bin

if [ ! -d results_Fe_nm ]; then
   mkdir  results_Fe_nm
fi
if [ ! -d $temp ]; then
   mkdir  $temp
fi
rm -rf $temp/*

# self-consistent calculation
cat > fe_nm.scf.in << EOF
 &control
    pseudo_dir = '$pseudo',
    outdir='$temp'
    prefix='fe_nm',
 /
 &system
    ibrav=  0, nat=  4, ntyp= 1,
    ecutwfc = 30.0, ecutrho = 300.0,
    occupations='smearing', smearing='mv', degauss=0.02,
    nspin=2, 
    nbnd = 16,
    starting_magnetization(1)= 0,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS angstrom
 4.053843 0.000000 0.000000
 0.000000 4.053843 0.000000 
 0.000000 0.000000 2.866500
ATOMIC_SPECIES
 Fe  1.  Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS crystal
 Fe   0.00  0.00  0.00
 Fe   0.50  0.50  0.00
 Fe   0.50  0.00  0.50 
 Fe   1.00  0.50  0.50
K_POINTS automatic
16 16 16 0 0 0
EOF
$bin/pw.x < fe_nm.scf.in  > results_Fe_nm/fe_nm.scf.out


