name: spyns
channels:
- defaults
- conda-forge
- matsci
dependencies:
- anaconda=4.4.0=np112py36_0
- ase=3.12.0=py36_0
- autopep8=1.3.2=py36_0
- blinker=1.4=py36_0
- brewer2mpl=1.4.1=py36_2
- certifi=2017.7.27.1=py36_0
- flake8=3.3.0=py36_0
- future=0.16.0=py36_1
- json-rpc=1.10.3=py36_0
- lockfile=0.12.2=py36_0
- monty=1.0.0=py36_2
- palettable=3.1.0=py_0
- pydispatcher=2.0.5=py36_0
- pydocstyle=2.0.0=py36_0
- python-daemon=2.1.2=py36_0
- python-language-server=0.4.2=py36_0
- pylama=7.4.3=py_0
- ruamel.yaml=0.15.34=py36_0
- spglib=1.9.9.44=py36_0
- tabulate=0.7.7=py36_0
- yapf=0.17.0=py36_0

