name: spyns
channels:
- defaults
- conda-forge
dependencies:
- anaconda=4.4.0=np112py36_0
- autopep8=1.3.2=py36_0
- brewer2mpl=1.4.1=py36_2
- certifi=2017.7.27.1=py36_0
- flake8=3.3.0=py36_0
- ruamel.yaml=0.15.33=py36_0
- tabulate=0.7.7=py36_0
- yapf=0.17.0=py36_0

