#!/bin/bash

rm -r energy.out.*.csv
n=1
for i in $(seq 2 1 200)
do
	if [ -e $i.scf.out ]; then

        	energy=$(grep "total energy " $i.scf.out | tail -n 2 | head -n 1 | awk '{print $5}')
  
        	if [ "$energy" == "Ry" ]; then
        
        	        energy=$(grep "total energy " $i.scf.out | tail -n 1 | awk '{print $4}')
                fi
                
	        printf "z-$n,24,$energy \n" >> energy.out.1x1x4.csv
        fi

	n=$(( $n + 1 ))
done

