#!/bin/bash
N=500
file="hinput"
for i in $(seq 000 100 1300)
do
  mkdir -p $i
  cd $i/.
  rm data*.txt
  cp ../{heisenberg,hinput,neighbor_lists.txt} .
  
  sed -i "1 c\temperature = $i" hinput
  sed -i "2 c\external_field(h) = 0.0" hinput
  sed -i "3 c\exchange_constant(1st_nn) = 18.2" hinput
  sed -i "4 c\exchange_constant(2nd_nn) = 10.3" hinput
  sed -i "5 c\iterations = 50000" hinput  
  sed -i "6 c\sampling_frequency = 50" hinput
  
  ./heisenberg>&log.$i&
  
  cd ../  
done

