#!/bin/bash
for i in $(seq 1 1 19)
do
	printf "awk '{print \$$i}' 1x1x4.list.edit \n" > awk_col
	bash awk_col > pattern_col
        paste -d '' pattern_col num_list > num_col
	paste -d "  " pattern_col num_col mn8au16_1x1x4.coords > coords


cat >mn8au16_1x1x4_$i.cif<< EOF
# generated using pymatgen
data_MnAu2
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   3.39483852
_cell_length_b   3.39483852
_cell_length_c  35.03452000
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   MnAu2
_chemical_formula_sum   'Mn8 Au16'
_cell_volume   409.39480045
_cell_formula_units_Z   8
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
EOF

	sed -i -e '/_atom_site_occupancy/rcoords' mn8au16_1x1x4_$i.cif


done

rm *_col coords

