#!/bin/bash
for n in  1024 1458 2000 3456 
do
	#printf "#T    MAvg    MVar    M2Avg    M2Var    M4Avg    M4Var \n" > m.$n
	awk '{print $1"    "$2"    "$3"    "$4"    "$5"    "$12"    "$13}' ../$n/data.txt > m.$n
done 


cat > binder.plot.gnu << EOF
#!/bin/bash
set term png
set output "binder.png"
set xlabel "T(K)"
set ylabel "U(T)"

binder(a,b) = 1.0 -  ( a /3.0*b*b )


plot 'm.1024' u 1:( binder(\$6,\$4) ) w l dt 2 t "N=1024",\
     'm.1458' u 1:( binder(\$6,\$4) ) w l dt 3 t "N=1458",\
     'm.2000' u 1:( binder(\$6,\$4) ) w l dt 4 t "N=2000",\
     'm.3456' u 1:( binder(\$6,\$4) ) w l dt 5 t "N=3456"

EOF

gnuplot binder.plot.gnu




