#!/bin/bash

temp='../temp'
pseudo='../pseudo'
results='results_MnAu2_nm'

if [ ! -d $results ]; then
   mkdir  $results
fi
if [ ! -d $temp ]; then
   mkdir  $temp
fi
rm -rf $temp/*

# self-consistent calculation
cat > mnau2_nm.scf.in << EOF
 &control
    calculation = 'scf',
    pseudo_dir = '$pseudo',
    outdir='$temp'
    prefix='mnau2',
 /
 &system
    ibrav=  0, 
    nat=  3, 
    ntyp= 3,
    ecutwfc = 60.0, ecutrho = 800.0,
    occupations='smearing', smearing='mv', degauss=0.02,
    nspin=2, 
    starting_magnetization(1)= 0.0,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS
 3.3701291084         0.0000000000         0.0000000000
 0.0000000000         3.3701291084         0.0000000000
-1.6850646988        -1.6850646988         4.3794687067
ATOMIC_SPECIES
 Mn    1.  Mn.pbe-sp-hgh.UPF
 Au    1.  Au.pbe-nd-rrkjus.UPF 
 Au1    1.  Au.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS crystal
Mn      0.000000000         0.000000000         0.000000000
Au     0.339999944         0.339999944         0.679999888
Au1     0.659999907         0.659999907         0.319999963
K_POINTS automatic
8 8 4 0 0 0
EOF

pw.x < mnau2_nm.scf.in  > $results/mnau2.scf.out

./run_MnAu2_nm-nscf
./run_MnAu2_nm-bands
