#!/bin/bash

temp='../temp'
pseudo='../pseudo'
results='results_MnAu2_fm'

# nonself-consistent calculation
cat > mnau2_fm.bands.in << EOF
 &control
    calculation = 'bands',
    pseudo_dir = '$pseudo',
    outdir='$temp'
    prefix='mnau2',
 /
 &system
    ibrav=  0, 
    nat=  3, 
    ntyp= 3,
    ecutwfc = 60.0, ecutrho = 800.0,
    occupations='smearing', smearing='mv', degauss=0.02,
    nbnd=10
    nspin=2, 
    starting_magnetization(1)= 0.8,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS
 3.3701291084         0.0000000000         0.0000000000
 0.0000000000         3.3701291084         0.0000000000
-1.6850646988        -1.6850646988         4.3794687067
ATOMIC_SPECIES
 Mn    1.  Mn.pbe-sp-hgh.UPF
 Au    1.  Au.pbe-nd-rrkjus.UPF 
 Au1    1.  Au.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS crystal
Mn      0.000000000         0.000000000         0.000000000
Au     0.339999944         0.339999944         0.679999888
Au1     0.659999907         0.659999907         0.319999963

K_POINTS {crystal_b}
6
  0.50  0.25  0.75  30 !W
  0.00  0.00  0.00  30 !G
  0.50  0.00  0.50  30 !X
  0.50  0.25  0.75  30 !W
  0.50  0.50  0.50  30 !L
  0.00  0.00  0.00  30 !G

EOF

pw.x < mnau2_fm.bands.in  > $results/mnau2.bands.out

cat > mnau2_fm.banddata.in << EOF
 &BANDS
    outdir='$temp '
    prefix='mnau2'
    filband='$results/mnau2_fm-bands.dat'
 /

EOF

bands.x < mnau2_fm.banddata.in > $results/mnau2_fm.banddata.out




