#!/bin/bash

temp='./temp'
pseudo='../pseudo'
results='results_MnAu2_fm'

# nonself-consistent calculation
cat > mnau2_fm.nscf.in << EOF
 &control
    calculation = 'nscf',
    pseudo_dir = '$pseudo',
    outdir='$temp'
    prefix='mnau2',
 /
 &system
    ibrav=  0, 
    nat=  3, 
    ntyp= 3,
    ecutwfc = 45.0, ecutrho = 300.0,
    occupations='smearing', smearing='mv', degauss=0.02,
    nspin=2, 
    starting_magnetization(1)= 1.0,
 /
 &electrons
    mixing_beta = 0.3 
 /
CELL_PARAMETERS angstrom
 3.3701291084         0.0000000000         0.0000000000
 0.0000000000         3.3701291084         0.0000000000
-1.6850646988        -1.6850646988         4.3794687067
ATOMIC_SPECIES
 Mn    1.  Mn.pbe-spn-kjpaw_psl.0.3.1.UPF
 Au    1.  Au.pbe-dn-kjpaw_psl.0.1.UPF
 Au1   1.  Au.pbe-dn-kjpaw_psl.0.1.UPF
ATOMIC_POSITIONS crystal
Mn      0.000000000         0.000000000         0.000000000
Au      0.339999944         0.339999944         0.679999888
Au1     0.659999907         0.659999907         0.319999963
K_POINTS automatic
16 16 16 0 0 0

EOF

mpirun -np 4 pw.x < mnau2_fm.nscf.in  > $results/mnau2.nscf.out

echo "Done nscf calculation, starting DOS ..."

cat > mnau2_fm.dos.in << EOF
&DOS
    outdir='$temp'
    prefix='mnau2'
    fildos='$results/mnau2.dos'
    degauss = 0.007d0,
    ngauss = 0
    DeltaE=0.1
 /

EOF


dos.x < mnau2_fm.dos.in  > $results/mnau2.dos.out


echo "Done DOS, starting pDOS ..."

cat > mnau2_fm.pdos.in << EOF
 &PROJWFC
    outdir='$temp '
    prefix='mnau2'
    degauss = 0.007d0,
    ngauss = 0
    DeltaE=0.1
 /

EOF


mpirun -np 4 projwfc.x < mnau2_fm.pdos.in  > $results/mnau2.pdos.out
mv mnau2.pdos_* $results/.


