#!/bin/bash
N=2048
mkdir -p Results
mkdir -p aucf_files 
rm -r Results/*
rm -r aucf_files/*
rm data.txt

for i in $(seq 500 100 1400)
do 
      mv ../$i/aucf.out aucf_files/$i 
      grep $i ../$i/data_$N.txt >> data.txt	
done

#gnuplot isingplot_r.gnu
#gnuplot isingplot_l.gnu
gnuplot isingplot.gnu

